services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: hookuser
      POSTGRES_PASSWORD: hookpass
      POSTGRES_DB: hookforge
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  pgdata:
